# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'

- task: GitVersion@5
  inputs:
    runtime: 'core'

- task: npmAuthenticate@0
  inputs:
    workingFile: '.npmrc'

- script: |
    set -e
    chmod u+x ./build/build.sh
    cd "$(Build.SourcesDirectory)"
    ./build/build.sh "$(GitVersion.SemVer)" "$(Build.SourceBranchName)"
  displayName: 'Build Script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.SourcesDirectory)/dist'
    artifact: '$(Build.Repository.Name)'

- task: GitHubRelease@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    gitHubConnection: 'git-chaseappio'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: 'v$(GitVersion.SemVer)'
    title: 'Chase $(Build.Repository.Name) v$(GitVersion.SemVer)'
    compareWith: 'lastFullRelease'
